#!/bin/bash

echo "Starting bspwmrc..."

# Get current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

sxhkd &
compton &

for monitor in $(bspc query -M); do
    bspc monitor $monitor -d A B C D
done

bspc config border_width         2
bspc config window_gap          20
bspc config top_padding         20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Background
feh --bg-fill "$DIR/firewatch-night.jpg"

# Panels
"$DIR/top-panel" &

# Start a terminal
termite &
