#! /bin/sh

sxhkd &
compton &

bspc monitor eDPI -d A B C D 
for monitor in $(bspc query -M); do
    bspc monitor $monitor -d A B C D
done

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

yabar &
feh --bg-fill ~/images/firewatch-night.jpg

# Start a terminal
termite &
